"""
Mock AI provider for AI Company OS.

MockProvider satisfies the AIProvider interface with fully deterministic,
pure-Python responses.  It uses no AI, no networking, and no external
libraries.  Identical requests always produce identical responses.

Purpose
-------
- Unit testing the provider abstraction layer without network calls.
- Development and CI environments where no API key is available.
- Demonstration of the provider contract in examples and documentation.

Response generation
-------------------
The provider inspects the task field of the ProviderRequest for keywords
and selects the most appropriate response template.  Templates are static
strings enriched with values from the request (role, task, objective,
constraints, expected_output).  No randomness is introduced.

Architecture reference: §2.10 LLM Gateway, §3 Layer 2 (Intelligence Layer).
"""

from typing import Any, Dict, List

from core.ai.provider import AIProvider, InvalidRequestError
from core.ai.provider_request import ProviderRequest
from core.ai.provider_response import ProviderResponse


# ---------------------------------------------------------------------------
# Keyword tables
# ---------------------------------------------------------------------------

_AUTH_KEYWORDS = frozenset([
    "auth", "authentication", "login", "logout", "register", "jwt",
    "oauth", "token", "session", "credential", "password", "signup",
])

_API_KEYWORDS = frozenset([
    "api", "endpoint", "rest", "route", "http", "request", "response",
    "openapi", "swagger", "graphql", "grpc", "webhook",
])

_DATABASE_KEYWORDS = frozenset([
    "database", "schema", "table", "sql", "db", "query", "migration",
    "index", "relation", "entity", "orm", "model", "record", "store",
])

_TEST_KEYWORDS = frozenset([
    "test", "testing", "spec", "coverage", "unit", "integration",
    "e2e", "assertion", "mock", "fixture", "qa", "quality",
])

_DEPLOY_KEYWORDS = frozenset([
    "deploy", "deployment", "ci", "cd", "pipeline", "infrastructure",
    "docker", "container", "kubernetes", "cloud", "server", "devops",
])

_REVIEW_KEYWORDS = frozenset([
    "review", "audit", "check", "inspect", "evaluate", "assess",
    "feedback", "critique", "analyse", "analyze",
])

_DOCUMENT_KEYWORDS = frozenset([
    "document", "documentation", "docs", "readme", "guide", "manual",
    "reference", "specification", "spec", "write", "draft",
])

_REFACTOR_KEYWORDS = frozenset([
    "refactor", "refactoring", "clean", "improve", "optimise",
    "optimize", "restructure", "extract", "simplify",
])

_SECURITY_KEYWORDS = frozenset([
    "security", "secure", "vulnerability", "vulnerable", "threat",
    "attack", "exploit", "permission", "access", "authorize", "authorise",
    "encrypt", "encryption", "sanitize", "sanitise",
])

_FRONTEND_KEYWORDS = frozenset([
    "frontend", "ui", "component", "react", "vue", "angular",
    "css", "html", "layout", "page", "interface", "style",
])


# ---------------------------------------------------------------------------
# Template builders (all ASCII-safe)
# ---------------------------------------------------------------------------

def _fmt_constraints(constraints: List[str]) -> str:
    if not constraints:
        return "No constraints specified."
    return "\n".join(f"  - {c}" for c in constraints)


def _fmt_expected(expected: str) -> str:
    return expected if expected.strip() else "Structured Markdown document."


def _build_header(request: ProviderRequest, doc_title: str) -> str:
    return (
        f"# {doc_title}\n\n"
        f"**Agent Role:** {request.role}  \n"
        f"**Task:** {request.task}  \n"
        f"**Generated by:** MockProvider v1  \n\n"
        "---\n\n"
        f"## Objective\n\n"
        f"{request.objective}\n"
    )


def _build_footer(request: ProviderRequest) -> str:
    parts = []
    if request.has_constraints():
        parts.append(
            "## Constraints Observed\n\n"
            + _fmt_constraints(request.constraints)
        )
    if request.has_expected_output():
        parts.append(
            f"## Expected Output Format\n\n"
            f"{request.expected_output}"
        )
    parts.append(
        "---\n\n"
        "_Generated by MockProvider -- AI Company OS_"
    )
    return "\n\n".join(parts)


def _auth_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Authentication API Design")
    body = """
## Overview

This document defines the REST API for a JWT-based authentication system.
The design provides user registration, login, token refresh, and logout.

## Endpoints

### POST /auth/register
Register a new user account.

Request body:
  email        (string, required)
  password     (string, required, min 8 chars)
  display_name (string, required)

Response 201 Created:
  user_id      (string, UUID)
  email        (string)
  created_at   (ISO-8601)

### POST /auth/login
Authenticate and receive JWT access and refresh tokens.

Request body:
  email    (string, required)
  password (string, required)

Response 200 OK:
  access_token  (string, JWT, expires in 15 min)
  refresh_token (string, JWT, expires in 7 days)
  token_type    ("Bearer")

### POST /auth/refresh
Exchange a valid refresh token for a new access token.

Request body:
  refresh_token (string, required)

Response 200 OK:
  access_token (string, JWT)
  expires_in   (integer, seconds)

### DELETE /auth/logout
Invalidate the caller's refresh token.

Headers:
  Authorization: Bearer {access_token}

Response 204 No Content

### GET /auth/me
Return the authenticated user's profile.

Headers:
  Authorization: Bearer {access_token}

Response 200 OK:
  user_id      (string)
  email        (string)
  display_name (string)
  created_at   (ISO-8601)

## Security Requirements

- Passwords hashed with bcrypt (cost factor 12 or higher)
- Access tokens signed with RS256
- Refresh tokens stored server-side and revocable
- Rate limit: 5 failed logins per IP per 60 seconds triggers lockout
- All endpoints served over HTTPS only
- CORS restricted to explicitly allowed origins

## Error Codes

  400 Bad Request         - Missing or malformed fields
  401 Unauthorized        - Invalid or expired token
  409 Conflict            - Email already registered
  422 Unprocessable Entity - Validation failure
  429 Too Many Requests   - Rate limit exceeded

## Implementation Notes

- Use RS256 (asymmetric) JWT, not HS256
- Store only refresh token hashes, never plaintext
- Implement token rotation on every refresh call
- Log all authentication events (success and failure) for audit
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _api_response(request: ProviderRequest) -> str:
    header = _build_header(request, "REST API Specification")
    body = """
## Overview

This specification defines the REST API contract for the requested service.
All endpoints follow REST conventions and return JSON responses.

## Base Configuration

  Base URL:       /api/v1
  Content-Type:   application/json
  Authentication: Bearer token (JWT)
  Versioning:     URI versioning (/api/v1, /api/v2)

## Standard Response Envelope

Success:
  {
    "success": true,
    "data": { ... },
    "meta": { "request_id": "uuid", "timestamp": "ISO-8601" }
  }

Error:
  {
    "success": false,
    "error": { "code": "ERROR_CODE", "message": "Human-readable message" },
    "meta": { "request_id": "uuid", "timestamp": "ISO-8601" }
  }

## Core Endpoints

### GET /api/v1/health
System health check. No authentication required.

Response 200 OK:
  status   ("ok" or "degraded")
  version  (string, semver)
  uptime   (integer, seconds)

### GET /api/v1/resources
List all resources with pagination.

Query parameters:
  page      (integer, default 1)
  per_page  (integer, default 20, max 100)
  sort      (string, field name)
  order     ("asc" or "desc")

Response 200 OK:
  items   (array of resource objects)
  total   (integer)
  page    (integer)
  pages   (integer)

### POST /api/v1/resources
Create a new resource.

Request body:
  name        (string, required)
  description (string, optional)
  metadata    (object, optional)

Response 201 Created:
  id          (string, UUID)
  name        (string)
  created_at  (ISO-8601)

### GET /api/v1/resources/{id}
Retrieve a single resource.

Response 200 OK - resource object
Response 404 Not Found - resource does not exist

### PATCH /api/v1/resources/{id}
Update a resource (partial update).

Request body: any subset of mutable fields.
Response 200 OK - updated resource object

### DELETE /api/v1/resources/{id}
Delete a resource.

Response 204 No Content
Response 404 Not Found - resource does not exist

## Error Codes

  400 Bad Request          - Malformed request body
  401 Unauthorized         - Missing or expired token
  403 Forbidden            - Insufficient permissions
  404 Not Found            - Resource does not exist
  409 Conflict             - Duplicate resource
  422 Unprocessable Entity - Validation error
  429 Too Many Requests    - Rate limit exceeded
  500 Internal Server Error - Unexpected server failure
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _database_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Database Schema Design")
    body = """
## Overview

This document defines the relational database schema for the requested system.
All tables follow consistent naming and field conventions.

## Technology

  Engine:    PostgreSQL 15+
  Charset:   UTF-8
  Collation: en_US.UTF-8

## Common Field Conventions

Every table includes:
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid()
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  is_deleted BOOLEAN NOT NULL DEFAULT false

The is_deleted field enables soft-delete. Hard deletes are never performed
on production data without explicit CEO approval.

## Core Tables

### users
Stores user accounts for authentication and profile data.

  id           UUID PRIMARY KEY
  email        VARCHAR(255) NOT NULL UNIQUE
  password_hash VARCHAR(255) NOT NULL
  display_name VARCHAR(100) NOT NULL
  status       VARCHAR(32) NOT NULL DEFAULT 'active'
  created_at   TIMESTAMPTZ NOT NULL
  updated_at   TIMESTAMPTZ NOT NULL

Indexes:
  users_email_idx UNIQUE ON (email)
  users_status_idx ON (status) WHERE is_deleted = false

### sessions
Tracks active user sessions and refresh tokens.

  id            UUID PRIMARY KEY
  user_id       UUID NOT NULL REFERENCES users(id)
  token_hash    VARCHAR(255) NOT NULL UNIQUE
  expires_at    TIMESTAMPTZ NOT NULL
  ip_address    INET
  user_agent    TEXT
  created_at    TIMESTAMPTZ NOT NULL

Indexes:
  sessions_user_id_idx ON (user_id)
  sessions_token_hash_idx UNIQUE ON (token_hash)
  sessions_expires_at_idx ON (expires_at)

### audit_log
Immutable log of all significant system events.

  id          UUID PRIMARY KEY
  actor_id    UUID REFERENCES users(id)
  action      VARCHAR(100) NOT NULL
  entity_type VARCHAR(100) NOT NULL
  entity_id   UUID
  payload     JSONB
  ip_address  INET
  created_at  TIMESTAMPTZ NOT NULL

Indexes:
  audit_log_actor_id_idx ON (actor_id)
  audit_log_entity_idx ON (entity_type, entity_id)
  audit_log_created_at_idx ON (created_at)

## Migration Strategy

  - Sequential numbered migration files: 0001_initial.sql, 0002_add_sessions.sql
  - Every migration is atomic and wrapped in a transaction
  - Each migration includes an explicit DOWN migration for rollback
  - Schema changes are never applied directly to production

## Indexing Strategy

  - All primary keys: B-Tree index (automatic)
  - All foreign keys: B-Tree index (explicit)
  - Status fields: Partial index WHERE is_deleted = false
  - Timestamp fields used for range queries: B-Tree index
  - Full-text search fields: GIN index with tsvector
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _test_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Test Plan and Strategy")
    body = """
## Overview

This document defines the testing strategy for the requested module.
Tests are organised into three levels: unit, integration, and end-to-end.

## Test Levels

### Unit Tests
Scope: Individual functions and classes in isolation.
Framework: pytest (or unittest where specified)
Coverage target: 90% branch coverage minimum

Key areas to cover:
  - All public methods with valid inputs
  - All error paths (invalid inputs, edge cases)
  - Boundary values (empty lists, zero, max values)
  - State transitions (before/after mutation)

### Integration Tests
Scope: Interactions between two or more components.
Environment: Local database (test schema), mocked external services

Key areas to cover:
  - Database read/write cycles
  - Cross-module event flows
  - Authentication middleware stack
  - API request/response round trips

### End-to-End Tests
Scope: Full user workflows through the running system.
Environment: Staging environment with test data fixtures

Key workflows to cover:
  - User registration and login
  - Core business operations
  - Error recovery and retry behaviour
  - Authentication token refresh

## Test Data Strategy

  - Fixtures defined in tests/fixtures/
  - Database state reset between test runs via transactions or truncation
  - No test depends on another test's side effects
  - All random values use seeded generators for reproducibility

## Naming Conventions

  Unit test files:        tests/unit/test_{module}.py
  Integration test files: tests/integration/test_{flow}.py
  E2E test files:         tests/e2e/test_{workflow}.py

Each test function name follows: test_{scenario}_{expected_outcome}
Example: test_login_with_invalid_password_returns_401

## Running Tests

  All tests:    python -m pytest tests/
  Unit only:    python -m pytest tests/unit/
  With coverage: python -m pytest --cov=core tests/

## Acceptance Criteria

  - All tests pass in CI before any merge to main
  - No test may be skipped without documented justification
  - Flaky tests are treated as bugs and fixed immediately
  - Coverage must not decrease below 90% in any pull request
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _deploy_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Deployment and CI/CD Plan")
    body = """
## Overview

This document defines the deployment strategy and CI/CD pipeline
for the requested system.

## Environments

  development:  Local developer machines
  staging:      Pre-production, mirrors production config
  production:   Live system, CEO-approved deployments only

## CI/CD Pipeline

### Stage 1: Build
  - Checkout code
  - Install dependencies (pip install -r requirements.txt)
  - Lint (flake8, mypy)
  - Format check (black --check)

### Stage 2: Test
  - Run unit tests (pytest tests/unit/)
  - Run integration tests (pytest tests/integration/)
  - Generate coverage report
  - Fail if coverage drops below 90%

### Stage 3: Package
  - Build Docker image
  - Tag image with git commit SHA and semantic version
  - Push image to container registry

### Stage 4: Deploy to Staging
  - Pull latest image on staging server
  - Run database migrations (alembic upgrade head)
  - Perform smoke tests
  - Notify team of staging deployment

### Stage 5: Deploy to Production
  - Requires CEO approval in the approval system
  - Perform blue-green deployment
  - Run health checks against new deployment
  - Rollback automatically if health checks fail within 5 minutes

## Rollback Strategy

  - Rollback trigger: health check failure or CEO instruction
  - Rollback target: previous known-good image tag
  - Database rollback: alembic downgrade -1 (only if migration is reversible)
  - Maximum rollback time: 3 minutes

## Infrastructure

  Containerisation:  Docker
  Orchestration:     Docker Compose (dev), Kubernetes (production)
  Secrets:           Environment variables injected at runtime (never in code)
  Monitoring:        Health endpoint /api/v1/health polled every 30 seconds

## Security

  - All secrets managed via environment variables or secrets manager
  - Container images scanned for vulnerabilities before deployment
  - Production network access restricted to approved IP ranges
  - All deployment events logged to audit trail
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _review_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Code Review Report")
    body = """
## Overview

This report documents the findings from the code review of the requested
module.  Findings are classified by severity: CRITICAL, HIGH, MEDIUM, LOW.

## Summary

  Critical findings:  0
  High findings:      2
  Medium findings:    3
  Low findings:       4
  Total:              9

## Findings

### HIGH: Missing input validation on public API boundary

Location: service layer, public methods
Issue: Public method parameters are not validated before processing.
       A caller passing None or an empty string will trigger an unhandled
       AttributeError deep inside the call stack.
Recommendation: Add explicit validation at every public method entry point.
                Raise ValueError with a descriptive message for invalid input.

### HIGH: Exception type too broad

Location: error handling blocks
Issue: Several except clauses catch the base Exception class.  This masks
       unexpected errors and makes debugging difficult.
Recommendation: Catch specific exception types.  Use a broad catch only
                at the top-level boundary, and always log the full traceback.

### MEDIUM: Missing type annotations

Location: Several function signatures
Issue: Return types and parameter types are not annotated.  This prevents
       static type checking from catching type errors.
Recommendation: Add type annotations to all public function signatures.
                Run mypy in CI to enforce annotation coverage.

### MEDIUM: Magic numbers without named constants

Location: Business logic
Issue: Numeric literals appear directly in logic (e.g. token expiry 900,
       rate limit 5).  Their meaning is not self-evident.
Recommendation: Define named constants with descriptive names at module level.

### MEDIUM: Incomplete docstrings

Location: All public classes and methods
Issue: Several public interfaces lack docstrings.  New contributors cannot
       understand their contracts without reading the implementation.
Recommendation: Add docstrings to all public classes and methods.  Include
                Args, Returns, and Raises sections where applicable.

### LOW: Unused import statements

Location: Module level
Issue: Several import statements reference modules not used in the file.
Recommendation: Remove unused imports.  Enable a linter rule to catch them.

## Approved Patterns

  - Data model uses dataclasses with frozen=True for immutable value objects.
  - Enum types inherit from (str, Enum) for serialisation compatibility.
  - All public exceptions inherit from a module-specific base exception class.

## Recommendation

Address HIGH findings before merging.  MEDIUM findings may be addressed
in a follow-up task if a deadline constraint applies.  LOW findings should
be addressed in the next available refactor session.
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _document_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Technical Documentation")
    body = """
## Overview

This document provides the technical reference for the requested module.
It is intended for engineers who will implement, test, or integrate with
this component.

## Purpose

This component is responsible for a well-defined domain within AI Company OS.
It exposes a clean public interface and has no knowledge of its callers.

## Public Interface

### Constructor

  ComponentName(*, dependency_a=None, dependency_b=None)

  All constructor parameters are keyword-only.  All are optional.
  When omitted, the component operates in standalone mode.

### Core Methods

  execute(request) -> Result
    Execute the primary operation.
    Args: request - A structured input object.
    Returns: A Result object containing the output and metadata.
    Raises: ComponentError on failure.

  status() -> Dict[str, Any]
    Return the current operational status.
    Returns: A dictionary with keys: healthy (bool), state (str),
             last_activity (datetime or None).

  history() -> List[Result]
    Return all results in execution order.
    Returns: A list of Result objects, oldest first.

  statistics() -> Dict[str, Any]
    Return aggregate metrics.
    Returns: total_requests (int), successful (int), failed (int).

## Configuration

No configuration files are used.  All settings are passed via constructor
keyword arguments.  There are no global state or module-level variables.

## Error Handling

All errors raised by this component inherit from ComponentError.
Callers should catch ComponentError as the base class.

  ComponentError           - Base error
  NotFoundError            - Requested item does not exist
  ValidationError          - Input failed validation
  StateError               - Operation not valid in current state

## Thread Safety

This component is not thread-safe.  Callers that share an instance across
threads are responsible for external synchronisation.

## Examples

  from core.component import ComponentName

  comp = ComponentName()
  result = comp.execute(request)
  print(result.summary())
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _refactor_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Refactoring Plan")
    body = """
## Overview

This document outlines the refactoring plan for the requested module.
All changes are behaviour-preserving: the public interface remains unchanged
and all existing tests continue to pass.

## Motivation

The current implementation has accumulated technical debt that makes it
harder to read, test, and extend.  This refactor addresses the root causes
without changing any externally observable behaviour.

## Changes Proposed

### 1. Extract helper functions from large methods

Target: Any method exceeding 30 lines of implementation.
Approach: Identify cohesive sub-operations and extract them into
          private helper methods with descriptive names.
Impact: Reduces cyclomatic complexity.  Enables targeted unit tests.

### 2. Replace magic literals with named constants

Target: Numeric and string literals embedded in business logic.
Approach: Define module-level constants with descriptive UPPER_SNAKE_CASE names.
Impact: Self-documenting code.  Single point of change for each value.

### 3. Consolidate duplicate logic

Target: Code blocks that appear in two or more places with minor variation.
Approach: Extract the common pattern into a single function parameterised
          by the variation.
Impact: Reduces maintenance surface.  Bugs fixed once, not twice.

### 4. Introduce explicit state validation

Target: Methods that assume internal state without checking.
Approach: Add guard clauses at method entry using descriptive error messages.
Impact: Fail-fast behaviour.  Clearer error messages for callers.

### 5. Align naming with domain terminology

Target: Variable and method names that use generic terms (data, item, obj).
Approach: Rename to reflect the domain concept they represent.
Impact: Code reads as domain description, not generic programming.

## Migration Path

  Step 1: Write additional tests to lock current behaviour.
  Step 2: Apply changes one at a time, running tests after each.
  Step 3: Review updated code for any regressions in readability.
  Step 4: Update docstrings to reflect the new structure.
  Step 5: Submit for CEO approval as a maintenance task.

## Risk Assessment

  Risk level: LOW
  - No public interface changes
  - All changes are additive (extract) or renaming
  - Full test coverage is enforced before and after
  - Each step is independently reversible
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _security_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Security Assessment")
    body = """
## Overview

This document presents the security assessment for the requested component.
Findings are prioritised by OWASP risk rating: Critical, High, Medium, Low.

## Threat Model

  Assets under protection:
    - User credentials and session tokens
    - Personally identifiable information (PII)
    - System configuration and secrets
    - Audit log integrity

  Threat actors considered:
    - Unauthenticated external attacker
    - Authenticated user exceeding their privilege scope
    - Compromised internal service

## Findings

### Authentication and Authorisation

  Status: REVIEW REQUIRED
  - Verify that all authenticated endpoints enforce token validation.
  - Confirm that resource ownership is checked, not just authentication.
  - Ensure privilege escalation paths do not exist in role assignment.

### Input Validation

  Status: REMEDIATION REQUIRED
  - All inputs entering the system from external sources must be validated
    and sanitised before processing.
  - Use allowlist validation, not denylist.
  - Parameterise all database queries.  No string concatenation in SQL.

### Secrets Management

  Status: COMPLIANT
  - No secrets detected in source code.
  - Configuration injected via environment variables at runtime.
  - Secrets must never appear in logs, event payloads, or memory records.

### Transport Security

  Status: ACTION REQUIRED
  - All external communication must use TLS 1.2 or higher.
  - HTTP Strict Transport Security (HSTS) must be configured.
  - Certificate pinning recommended for mobile clients.

### Logging and Audit

  Status: COMPLIANT
  - Authentication events are logged with actor, action, and timestamp.
  - Audit log is append-only and write-protected.
  - Sensitive fields (passwords, tokens) are excluded from logs.

## Recommendations

  1. Complete input validation remediation before production deployment.
  2. Perform penetration test on authentication endpoints.
  3. Review all privilege assignment paths with security lead.
  4. Establish automated dependency vulnerability scanning in CI.

## Compliance Notes

  Findings in this report must be resolved before CEO approval is
  requested for any production deployment of this component.
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _frontend_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Frontend Component Design")
    body = """
## Overview

This document defines the component architecture and design specification
for the requested frontend module.

## Component Hierarchy

  Page
    Layout
      NavigationBar
        Logo
        NavLinks
        AuthButton
      MainContent
        PageHeader
        ContentArea (slot)
        ActionBar
      Footer

## State Management

  Local state:   React useState / Vue reactive for UI-only state
  Shared state:  Context API / Pinia store for cross-component data
  Server state:  React Query / SWR for API-backed data with caching

## Component Specification

### NavigationBar
  Props:    title (string), links (NavLink[]), isAuthenticated (boolean)
  Events:   onLogout, onNavigate
  Behaviour: Highlights active link based on current route.
             Collapses to hamburger menu below 768px viewport width.

### ContentArea
  Props:   loading (boolean), error (string | null), children (ReactNode)
  Behaviour: Shows loading skeleton while data is fetching.
             Shows error state with retry button on failure.
             Renders children when data is available.

### ActionBar
  Props:   actions (Action[]), disabled (boolean)
  Events:  onAction(actionId)
  Behaviour: Disables all actions when disabled=true.
             Confirms destructive actions with a dialog before emitting.

## Design System

  Typography:   System font stack, 16px base, 1.5 line height
  Colours:      Primary #2563EB, Surface #0F1117, Text #E5E7EB
  Spacing:      4px base unit (4, 8, 12, 16, 24, 32, 48, 64)
  Border radius: 4px (small), 8px (default), 12px (large)
  Shadows:      0 1px 3px rgba(0,0,0,0.3) (elevation-1)

## Accessibility

  - All interactive elements have accessible names (aria-label or visible text)
  - Keyboard navigation supported on all interactive elements
  - Focus indicator visible on all focusable elements
  - Colour contrast ratio >= 4.5:1 for all text

## Testing

  - Unit tests for all non-trivial component logic
  - Integration tests for data-bound components
  - Snapshot tests for layout-critical components
  - Accessibility tests using axe-core
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


def _default_response(request: ProviderRequest) -> str:
    header = _build_header(request, "Task Execution Report")
    body = f"""
## Task Summary

This report documents the analysis and execution plan for the requested task.

Task received: {request.task}

## Analysis

The task has been analysed in the context of the stated objective.
The following approach is recommended based on best engineering practices
and the constraints provided.

## Recommended Approach

### Step 1: Clarify scope and acceptance criteria

Before implementation begins, confirm:
  - The exact deliverable expected from this task
  - The definition of "done" for this task
  - Any dependencies that must be resolved first
  - The priority relative to other active tasks

### Step 2: Design before implementation

Produce a short design document covering:
  - The data model involved
  - The public interface to be built or modified
  - The sequence of operations
  - The error handling strategy

### Step 3: Implementation

Follow these principles:
  - Single responsibility: each function or class does one thing
  - Explicit over implicit: avoid magic, favour clear naming
  - Type-safe: annotate all function signatures
  - Testable: design for unit testing from the start

### Step 4: Testing

Write tests at three levels:
  - Unit tests: every public method, including error paths
  - Integration tests: interactions with dependencies
  - Regression tests: any previous bug fixes

### Step 5: Documentation and review

  - Update docstrings and any affected documentation
  - Submit for peer review before requesting CEO approval
  - Record the decision and its rationale in company memory

## Risk Assessment

  Risk level: MEDIUM (depends on task scope)
  - Identified dependency: {request.context if request.context else 'None noted'}
  - Mitigation: Confirm requirements before beginning implementation

## Completion Criteria

This task is complete when:
  - All acceptance criteria are met
  - All tests pass with no regressions
  - Documentation is up to date
  - The output has been submitted for approval
"""
    footer = _build_footer(request)
    return header + body + "\n" + footer


# ---------------------------------------------------------------------------
# Keyword detection
# ---------------------------------------------------------------------------

def _detect_category(task: str) -> str:
    words = frozenset(task.lower().split())

    if words & _AUTH_KEYWORDS:
        return "auth"
    if words & _SECURITY_KEYWORDS:
        return "security"
    if words & _DATABASE_KEYWORDS:
        return "database"
    if words & _TEST_KEYWORDS:
        return "test"
    if words & _DEPLOY_KEYWORDS:
        return "deploy"
    if words & _REVIEW_KEYWORDS:
        return "review"
    if words & _DOCUMENT_KEYWORDS:
        return "document"
    if words & _REFACTOR_KEYWORDS:
        return "refactor"
    if words & _FRONTEND_KEYWORDS:
        return "frontend"
    if words & _API_KEYWORDS:
        return "api"
    return "default"


_GENERATORS: Dict[str, Any] = {
    "auth": _auth_response,
    "api": _api_response,
    "database": _database_response,
    "test": _test_response,
    "deploy": _deploy_response,
    "review": _review_response,
    "document": _document_response,
    "refactor": _refactor_response,
    "security": _security_response,
    "frontend": _frontend_response,
    "default": _default_response,
}


# ---------------------------------------------------------------------------
# MockProvider
# ---------------------------------------------------------------------------

class MockProvider(AIProvider):
    """
    Deterministic AI provider for testing and development.

    Returns structured Markdown responses based on keyword detection in the
    ProviderRequest.task field.  Identical inputs always produce identical
    outputs.  No randomness, no networking, no AI.

    The provider is always healthy (health() returns True).  It never raises
    ProviderUnavailableError.  It raises InvalidRequestError only if the
    request fails basic validation.
    """

    _PROVIDER_NAME = "MockProvider"
    _MODEL_NAME = "mock-v1"
    _TEMPERATURE = 0.0

    def name(self) -> str:
        """Return the stable provider identifier."""
        return self._PROVIDER_NAME

    def health(self) -> bool:
        """Always returns True -- MockProvider is always available."""
        return True

    def generate(self, request: ProviderRequest) -> ProviderResponse:
        """
        Generate a deterministic response for the given request.

        Args:
            request: The structured input from the agent.

        Returns:
            A ProviderResponse with deterministic content.

        Raises:
            InvalidRequestError: If the request fails validation.
        """
        try:
            request.validate()
        except Exception as exc:
            raise InvalidRequestError(str(exc)) from exc

        content = self._generate_content(request)
        tokens_used = len(content.split())
        exec_time = self._compute_execution_time(request)

        return ProviderResponse(
            content=content,
            tokens_used=tokens_used,
            provider_name=self._PROVIDER_NAME,
            execution_time=exec_time,
            metadata=self._make_metadata(request),
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_content(self, request: ProviderRequest) -> str:
        """Select and render the appropriate response template."""
        category = _detect_category(request.task)
        generator = _GENERATORS.get(category, _default_response)
        return generator(request)

    def _compute_execution_time(self, request: ProviderRequest) -> float:
        """Compute a deterministic execution time from the request task."""
        base = 0.05
        step = (len(request.task) % 10) * 0.01
        return round(base + step, 3)

    def _make_metadata(self, request: ProviderRequest) -> Dict[str, Any]:
        """Build provider metadata for the response."""
        return {
            "model": self._MODEL_NAME,
            "temperature": self._TEMPERATURE,
            "deterministic": True,
            "provider": self._PROVIDER_NAME,
            "category": _detect_category(request.task),
            "role": request.role,
            "constraint_count": request.constraint_count(),
        }
