"""
Artifact template rendering helpers for AI Company OS.

All methods in ArtifactTemplate are pure static functions. They accept
structured Python values and return Markdown-formatted text fragments.
They have no side effects and no dependencies on engine or registry state.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional


class ArtifactTemplate:
    """
    Collection of static Markdown rendering helpers used by ArtifactEngine.

    Each method accepts plain Python values and returns a Markdown string
    fragment suitable for inclusion in an Artifact's content field.
    All returned strings are ASCII-safe.
    """

    @staticmethod
    def render_header(
        artifact_type_label: str,
        title: str,
        project_id: Optional[str],
        generated_by: str,
        version: int,
        created_at: datetime,
    ) -> str:
        """Render a standardized document header block."""
        project_line = (
            f"**Project ID:** {project_id}"
            if project_id
            else "**Project ID:** N/A (company-wide)"
        )
        ts = created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        return (
            f"# {artifact_type_label}: {title}\n\n"
            f"{project_line}  \n"
            f"**Generated by:** {generated_by}  \n"
            f"**Version:** {version}  \n"
            f"**Generated at:** {ts}\n\n"
            "---\n"
        )

    @staticmethod
    def render_section(heading: str, content: str, level: int = 2) -> str:
        """Render a document section with a Markdown heading."""
        prefix = "#" * max(1, level)
        return f"\n{prefix} {heading}\n\n{content}\n"

    @staticmethod
    def render_key_value(pairs: Dict[str, Any]) -> str:
        """Render a mapping as Markdown bold-label bullet points."""
        if not pairs:
            return "_No data available._"
        lines = [f"- **{k}:** {v}" for k, v in pairs.items()]
        return "\n".join(lines)

    @staticmethod
    def render_task_table(tasks: List[Any]) -> str:
        """Render a list of Task objects as a Markdown table."""
        if not tasks:
            return "_No tasks found._"
        rows = [
            "| # | Title | Status | Priority | Assigned To |",
            "|---|-------|--------|----------|-------------|",
        ]
        for i, task in enumerate(tasks, 1):
            status = task.status.value if hasattr(task.status, "value") else str(task.status)
            priority = task.priority.value if hasattr(task.priority, "value") else str(task.priority)
            rows.append(
                f"| {i} | {task.title} | {status} | {priority} | {task.assigned_agent} |"
            )
        return "\n".join(rows)

    @staticmethod
    def render_bullet_list(items: List[str], empty_message: str = "_None._") -> str:
        """Render a list of strings as Markdown bullet points."""
        if not items:
            return empty_message
        return "\n".join(f"- {item}" for item in items)

    @staticmethod
    def render_numbered_list(items: List[str], empty_message: str = "_None._") -> str:
        """Render a list of strings as a Markdown numbered list."""
        if not items:
            return empty_message
        return "\n".join(f"{i}. {item}" for i, item in enumerate(items, 1))

    @staticmethod
    def render_risk_list(risks: List[Any]) -> str:
        """Render a list of Risk objects as a Markdown table."""
        if not risks:
            return "_No risks identified._"
        rows = [
            "| Category | Level | Description |",
            "|----------|-------|-------------|",
        ]
        for risk in risks:
            cat = risk.category.value if hasattr(risk.category, "value") else str(risk.category)
            level = risk.level.value if hasattr(risk.level, "value") else str(risk.level)
            rows.append(f"| {cat} | {level} | {risk.description} |")
        return "\n".join(rows)

    @staticmethod
    def render_department_list(departments: List[Any]) -> str:
        """Render a list of DepartmentRequirement objects as bullet points."""
        if not departments:
            return "_No departments specified._"
        lines = []
        for dr in departments:
            dept = dr.department.value if hasattr(dr.department, "value") else str(dr.department)
            critical = " **(Critical)**" if dr.is_critical else ""
            lines.append(f"- **{dept}**{critical}: {dr.rationale}")
        return "\n".join(lines)

    @staticmethod
    def render_decision_list(decisions: List[Any]) -> str:
        """Render a list of Decision objects as Markdown bullet points."""
        if not decisions:
            return "_No decisions found._"
        lines = []
        for d in decisions:
            status = d.status.value if hasattr(d.status, "value") else str(d.status)
            rec = f" -> **{d.recommendation}**" if d.recommendation else ""
            lines.append(f"- [{status}] {d.title}{rec}")
        return "\n".join(lines)

    @staticmethod
    def render_memory_list(entries: List[Any]) -> str:
        """Render a list of MemoryEntry objects as Markdown bullet points."""
        if not entries:
            return "_No memory entries found._"
        lines = []
        for e in entries:
            cat = e.category.value if hasattr(e.category, "value") else str(e.category)
            tags = ", ".join(sorted(e.tags)) if e.tags else "none"
            lines.append(f"- **[{cat}]** {e.title} _(tags: {tags})_")
        return "\n".join(lines)

    @staticmethod
    def render_workflow_list(workflows: List[Any]) -> str:
        """Render a list of Workflow objects as Markdown bullet points."""
        if not workflows:
            return "_No workflows found._"
        lines = []
        for wf in workflows:
            status = wf.status.value if hasattr(wf.status, "value") else str(wf.status)
            progress = round(wf.progress * 100, 1)
            stage = wf.current_stage.name if wf.current_stage else "Completed"
            lines.append(
                f"- **{wf.name}** [{status}] -- {progress}% complete -- Current stage: {stage}"
            )
        return "\n".join(lines)

    @staticmethod
    def render_footer(generated_by: str) -> str:
        """Render a standard document footer."""
        return f"\n---\n\n_Generated by {generated_by} -- AI Company OS_\n"

    @staticmethod
    def render_two_column_table(
        header_left: str, header_right: str, rows: List[tuple]
    ) -> str:
        """Render a two-column Markdown table."""
        if not rows:
            return "_No data._"
        lines = [
            f"| {header_left} | {header_right} |",
            "|---|---|",
        ]
        for left, right in rows:
            lines.append(f"| {left} | {right} |")
        return "\n".join(lines)
