"""
Company event model for AI Company OS.

Company events are the observable record of every significant step the
Company Orchestrator takes while fulfilling a CEO request. They are
emitted in real time during new_request() and recorded in the
CompanySession's event log. The complete event log is the authoritative,
ordered history of what the company did and when.

Events are immutable once emitted. The orchestrator never removes or
modifies a recorded event. The session's event list is append-only.

Architecture reference: §2.8 Event Bus, §10 Event Flow,
§3 Layer 3 (Infrastructure Layer).
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional
from uuid import uuid4


class CompanyEventType(str, Enum):
    """
    All observable event types emitted by the Company Orchestrator.

    Events are named from the perspective of what the company just did —
    they record a completed fact, not an intention. This naming convention
    makes the event log self-explanatory: each entry describes a step that
    has already occurred.

    Lifecycle event groups:

    Company lifecycle:
        COMPANY_STARTED     — The company runtime was started.
        COMPANY_STOPPED     — The company runtime was stopped.

    Request lifecycle:
        REQUEST_RECEIVED    — A new CEO request was accepted.
        REQUEST_COMPLETED   — The full orchestration flow completed.
        REQUEST_FAILED      — The orchestration flow failed with an error.

    Planning:
        PROJECT_ANALYZED    — PlannerEngine produced a ProjectBlueprint.
        PROJECT_CREATED     — ExecutiveEngine created a Project record.

    Staffing:
        DEPARTMENT_PROVISIONED — A department was created in the registry.
        EMPLOYEE_HIRED         — An employee was added to the workforce.

    Execution:
        TASK_CREATED    — A Task was created by the Executive Engine.
        TASK_ASSIGNED   — A Task was formally assigned to an employee.
        RUNTIME_STARTED — An AgentRuntime session was started for an employee.
        RUNTIME_STOPPED — An AgentRuntime session was stopped.

    Discussion:
        DISCUSSION_STARTED  — A DiscussionEngine discussion was opened.
        DISCUSSION_FINISHED — A DiscussionEngine discussion was closed.

    Project:
        PROJECT_FINISHED — The session's project was marked complete.
    """

    COMPANY_STARTED = "COMPANY_STARTED"
    COMPANY_STOPPED = "COMPANY_STOPPED"
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"
    PROJECT_ANALYZED = "PROJECT_ANALYZED"
    PROJECT_CREATED = "PROJECT_CREATED"
    DEPARTMENT_PROVISIONED = "DEPARTMENT_PROVISIONED"
    EMPLOYEE_HIRED = "EMPLOYEE_HIRED"
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    RUNTIME_STARTED = "RUNTIME_STARTED"
    RUNTIME_STOPPED = "RUNTIME_STOPPED"
    DISCUSSION_STARTED = "DISCUSSION_STARTED"
    DISCUSSION_FINISHED = "DISCUSSION_FINISHED"
    PROJECT_FINISHED = "PROJECT_FINISHED"

    def __str__(self) -> str:
        return self.value

    def is_terminal(self) -> bool:
        """Return True if this event marks the end of a request lifecycle."""
        return self in {
            CompanyEventType.REQUEST_COMPLETED,
            CompanyEventType.REQUEST_FAILED,
        }

    def is_error(self) -> bool:
        """Return True if this event indicates a failure condition."""
        return self == CompanyEventType.REQUEST_FAILED

    def is_company_lifecycle(self) -> bool:
        """Return True if this event relates to the company runtime itself."""
        return self in {
            CompanyEventType.COMPANY_STARTED,
            CompanyEventType.COMPANY_STOPPED,
        }


@dataclass(frozen=True)
class CompanyEvent:
    """
    Immutable record of a single observable step performed by the orchestrator.

    Every step the Company Orchestrator takes during a request is recorded
    as a CompanyEvent and appended to the active CompanySession's event log.
    Events are never modified or removed once recorded.

    The payload carries step-specific detail in a flexible dict, allowing
    each event type to document what it produced without requiring a separate
    class per event type.

    Attributes:
        id: Unique identifier (UUID string). Generated by the factory method.
        event_type: The category of event. Determines how the orchestrator
            and its consumers interpret the payload.
        timestamp: UTC timestamp of when this event was emitted.
        session_id: ID of the CompanySession this event belongs to.
            None for company-lifecycle events (STARTED, STOPPED) that
            are emitted outside the scope of a specific request.
        payload: Step-specific detail. Keys and value types vary by event
            type. Always a dict; empty for events with no further detail.
    """

    id: str
    event_type: CompanyEventType
    timestamp: datetime
    session_id: Optional[str] = None
    payload: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def create(
        cls,
        event_type: CompanyEventType,
        session_id: Optional[str] = None,
        payload: Optional[Dict[str, Any]] = None,
    ) -> "CompanyEvent":
        """
        Factory method for creating a new CompanyEvent with a generated ID
        and current UTC timestamp.

        Args:
            event_type: The type of event to record.
            session_id: Optional session this event belongs to.
            payload: Optional payload dict. Defaults to empty dict.

        Returns:
            A new, immutable CompanyEvent.
        """
        return cls(
            id=str(uuid4()),
            event_type=event_type,
            timestamp=datetime.now(timezone.utc),
            session_id=session_id,
            payload=payload or {},
        )

    def is_terminal(self) -> bool:
        """Delegate to event_type.is_terminal()."""
        return self.event_type.is_terminal()

    def is_error(self) -> bool:
        """Delegate to event_type.is_error()."""
        return self.event_type.is_error()

    def get_payload_value(self, key: str, default: Any = None) -> Any:
        """
        Return a value from the payload dict by key.

        Args:
            key: The key to look up.
            default: Value to return if key is absent. Default: None.

        Returns:
            The value, or default if the key is not present.
        """
        return self.payload.get(key, default)
