"""
StreamEvent model for AI Company OS Event Stream.

A StreamEvent is the atomic unit of communication in the Event Stream.
Every producer publishes StreamEvents; every consumer receives StreamEvents.
Events are immutable once created.

Architecture reference: §2.8 Event Bus, §10 Event Flow, §6 Communication Model.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from uuid import uuid4

from core.stream_channel import StreamChannel


@dataclass(frozen=True)
class StreamEvent:
    """
    Immutable record of a single event published to the Event Stream.

    Every system module that participates in the Event Stream creates
    StreamEvents and publishes them via EventStream.publish(). Consumers
    receive StreamEvents through their registered channel subscriptions.

    Events are immutable after creation. The EventStream's history is an
    append-only sequence of StreamEvents — no event is ever modified or
    removed once published.

    Attributes:
        id:        Unique identifier (UUID string). Generated by create().
        source:    Identity of the publishing component (e.g., "Planner",
                   "WorkflowEngine", "DiscussionEngine", "CEO").
        category:  The StreamChannel this event belongs to. Determines
                   which subscribers receive it.
        timestamp: UTC timestamp of when this event was created. Set
                   automatically by create().
        payload:   Arbitrary event-specific detail. Always a dict; empty
                   for events that carry no additional context beyond their
                   source and category.
    """

    id: str
    source: str
    category: StreamChannel
    timestamp: datetime
    payload: Dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def create(
        cls,
        source: str,
        category: StreamChannel,
        payload: Optional[Dict[str, Any]] = None,
    ) -> "StreamEvent":
        """
        Factory method producing a new StreamEvent with a generated ID
        and the current UTC timestamp.

        Args:
            source:   The identity of the publishing component. Must be
                      a non-empty string.
            category: The StreamChannel this event belongs to.
            payload:  Optional event-specific detail. Defaults to empty dict.

        Returns:
            A new, immutable StreamEvent.
        """
        return cls(
            id=str(uuid4()),
            source=source,
            category=category,
            timestamp=datetime.now(timezone.utc),
            payload=payload or {},
        )

    # ------------------------------------------------------------------
    # Query helpers
    # ------------------------------------------------------------------

    def is_from(self, source: str) -> bool:
        """Return True if this event was published by the given source."""
        return self.source == source

    def is_in_channel(self, channel: StreamChannel) -> bool:
        """Return True if this event belongs to the given channel."""
        return self.category == channel

    def get_payload_value(self, key: str, default: Any = None) -> Any:
        """
        Return a value from the payload dict by key.

        Args:
            key:     The key to look up.
            default: Value returned when key is absent. Default: None.

        Returns:
            The payload value, or default.
        """
        return self.payload.get(key, default)

    def has_payload(self) -> bool:
        """Return True if this event carries any payload data."""
        return bool(self.payload)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> Dict[str, Any]:
        """Return a compact dict representation suitable for logging."""
        return {
            "id": self.id,
            "source": self.source,
            "category": str(self.category),
            "timestamp": self.timestamp.isoformat(),
            "payload_keys": list(self.payload.keys()),
            "has_payload": self.has_payload(),
        }
