"""
Artifact Generation Engine demo for AI Company OS.

Demonstrates generating:
  1. PRD              - Product Requirements Document
  2. Technical Spec   - System architecture and design
  3. API Specification - REST endpoint catalog
  4. CEO Report       - Company-wide executive status report

Run:
    python examples/demo_artifacts.py
"""

from datetime import datetime, timezone
from uuid import uuid4

from core.artifact_engine import ArtifactEngine
from core.artifact_type import ArtifactType
from core.decision_engine import DecisionEngine
from core.decision_option import DecisionOption
from core.executive_engine import ExecutiveEngine
from core.memory_category import MemoryCategory
from core.memory_engine import MemoryEngine
from core.memory_entry import MemoryEntry
from core.memory_scope import MemoryScope
from core.planner_engine import PlannerEngine
from core.task import Priority
from core.workflow_engine import WorkflowEngine
from core.workflow_template import WorkflowTemplate


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_DIVIDER = "=" * 70
_THIN = "-" * 70


def print_divider(label: str = "") -> None:
    if label:
        pad = (_DIVIDER[:3] + " " + label + " ").ljust(69) + "="
        print(pad)
    else:
        print(_DIVIDER)


def print_artifact_summary(artifact) -> None:
    s = artifact.summary()
    print(f"  Type         : {s['type']}")
    print(f"  Title        : {s['title']}")
    print(f"  Version      : {s['version']}")
    print(f"  Project ID   : {s['project_id'] or 'N/A (company-wide)'}")
    print(f"  Generated by : {s['generated_by']}")
    print(f"  Words        : {s['word_count']}")
    print(f"  Lines        : {s['line_count']}")
    print(f"  Created at   : {s['created_at']}")
    print(f"  Artifact ID  : {s['id']}")


def print_content_preview(artifact, lines: int = 25) -> None:
    content_lines = artifact.content.splitlines()
    preview = content_lines[:lines]
    for line in preview:
        print(line)
    if len(content_lines) > lines:
        remaining = len(content_lines) - lines
        print(f"  ... [{remaining} more lines]")


# ---------------------------------------------------------------------------
# Setup: Create real engines with representative data
# ---------------------------------------------------------------------------

def setup_engines():
    """Create and seed all engines for the demo."""
    print("Setting up engines...")

    # Executive Engine + Project
    ee = ExecutiveEngine()
    proj = ee.create_project(
        title="E-Commerce Platform",
        description=(
            "Build a full-featured e-commerce platform with product catalog, "
            "shopping cart, user authentication, payment processing, and order management."
        ),
        objective=(
            "Deliver a production-ready e-commerce platform with Stripe payments, "
            "OAuth2 authentication, real-time inventory tracking, and mobile-responsive design."
        ),
        priority=Priority.HIGH,
    )

    t1 = ee.create_task(
        proj.id, "User Authentication Module",
        "Implement JWT-based authentication with OAuth2 social login support.",
        "Alice Chen", Priority.HIGH,
    )
    t2 = ee.create_task(
        proj.id, "Product Catalog Service",
        "Build CRUD API for products with search, filtering, and pagination.",
        "Bob Kumar", Priority.HIGH, dependencies=[t1.id],
    )
    t3 = ee.create_task(
        proj.id, "Payment Gateway Integration",
        "Integrate Stripe payment processing with webhooks and refund support.",
        "Alice Chen", Priority.CRITICAL, dependencies=[t1.id],
    )
    t4 = ee.create_task(
        proj.id, "Order Management System",
        "Build order creation, tracking, and fulfillment workflows.",
        "Carol Diaz", Priority.HIGH, dependencies=[t2.id, t3.id],
    )
    t5 = ee.create_task(
        proj.id, "Frontend Shopping Cart",
        "React-based shopping cart with real-time inventory validation.",
        "Carol Diaz", Priority.MEDIUM, dependencies=[t2.id],
    )

    ee.assign_task(t1.id, "Alice Chen")
    ee.assign_task(t2.id, "Bob Kumar")
    ee.assign_task(t3.id, "Alice Chen")

    print(f"  Project created: {proj.title} (ID: {proj.id[:8]}...)")
    print(f"  Tasks created: {len(proj.tasks)}")

    # Memory Engine
    me = MemoryEngine()
    me.store(MemoryEntry(
        id=str(uuid4()),
        title="Architecture Decision: Microservices vs Monolith",
        category=MemoryCategory.DECISION,
        scope=MemoryScope.GLOBAL,
        author="CEO",
        content="Decided to start with a modular monolith and extract services when scale demands it.",
        tags={"architecture", "decision", "monolith"},
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    ))
    me.store(MemoryEntry(
        id=str(uuid4()),
        title="Lesson: Test-Driven Development improves delivery speed",
        category=MemoryCategory.LESSON,
        scope=MemoryScope.GLOBAL,
        author="EngineeringLead",
        content="Writing tests first reduced debugging time by 40% in Sprint 12.",
        tags={"lesson", "testing", "tdd"},
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    ))
    print(f"  Memory entries: {me.count()}")

    # Decision Engine
    de = DecisionEngine(memory_engine=me)
    dec = de.create_decision(
        title="Choose payment processor for e-commerce platform",
        options=[
            DecisionOption(
                title="Stripe",
                advantages=["Developer-friendly API", "Strong fraud detection", "Excellent docs"],
                disadvantages=["Higher per-transaction fee"],
                estimated_risk="LOW",
                estimated_cost="MEDIUM",
            ),
            DecisionOption(
                title="PayPal",
                advantages=["Wide user adoption", "Established trust"],
                disadvantages=["Complex API", "Redirect-based checkout"],
                estimated_risk="LOW",
                estimated_cost="LOW",
            ),
        ],
        project_id=proj.id,
    )
    de.evaluate(dec.id)
    de.recommend(dec.id)
    print(f"  Decision created: {dec.title}")

    # Workflow Engine
    we = WorkflowEngine(memory_engine=me, decision_engine=de)
    wf = we.create_workflow(
        name="E-Commerce Platform Build",
        description="Full development lifecycle for the e-commerce platform.",
        template=WorkflowTemplate.SOFTWARE_PROJECT,
    )
    we.start(wf.id)
    we.advance(wf.id)
    print(f"  Workflow started: {wf.name}")

    # Planner Engine
    pe = PlannerEngine()
    print("  PlannerEngine ready.")

    # Artifact Engine (full configuration)
    engine = ArtifactEngine(
        executive_engine=ee,
        planner_engine=pe,
        workflow_engine=we,
        memory_engine=me,
        decision_engine=de,
    )

    return engine, proj.id


# ---------------------------------------------------------------------------
# Demo sections
# ---------------------------------------------------------------------------

def demo_prd(engine, project_id: str) -> None:
    print_divider()
    print("DEMO 1: Product Requirements Document (PRD)")
    print_divider()
    print()

    artifact = engine.generate_prd(project_id)

    print("--- Artifact Metadata ---")
    print_artifact_summary(artifact)
    print()
    print("--- Content Preview (first 30 lines) ---")
    print()
    print_content_preview(artifact, lines=30)
    print()


def demo_technical_spec(engine, project_id: str) -> None:
    print_divider()
    print("DEMO 2: Technical Specification")
    print_divider()
    print()

    artifact = engine.generate_technical_specification(project_id)

    print("--- Artifact Metadata ---")
    print_artifact_summary(artifact)
    print()
    print("--- Content Preview (first 30 lines) ---")
    print()
    print_content_preview(artifact, lines=30)
    print()


def demo_api_spec(engine, project_id: str) -> None:
    print_divider()
    print("DEMO 3: API Specification")
    print_divider()
    print()

    artifact = engine.generate_api_specification(project_id)

    print("--- Artifact Metadata ---")
    print_artifact_summary(artifact)
    print()
    print("--- Content Preview (first 30 lines) ---")
    print()
    print_content_preview(artifact, lines=30)
    print()


def demo_ceo_report(engine) -> None:
    print_divider()
    print("DEMO 4: CEO Report (Company-Wide)")
    print_divider()
    print()

    artifact = engine.generate_ceo_report(company_name="AI Company OS")

    print("--- Artifact Metadata ---")
    print_artifact_summary(artifact)
    print()
    print("--- Content Preview (first 40 lines) ---")
    print()
    print_content_preview(artifact, lines=40)
    print()


def demo_engine_history(engine) -> None:
    print_divider()
    print("ENGINE HISTORY & STATISTICS")
    print_divider()
    print()

    history = engine.history()
    print(f"Total artifacts generated: {len(history)}")
    print()
    print("Artifact log:")
    for a in history:
        label = ArtifactType(a.type).label()
        proj = a.project_id[:8] + "..." if a.project_id else "N/A"
        print(f"  [{a.version:2d}] {label:<35} | project: {proj} | words: {a.word_count()}")

    print()
    stats = engine.statistics()
    print("Type counts:")
    for t, count in stats["type_counts"].items():
        if count > 0:
            print(f"  {t:<35} : {count}")
    print(f"Unique projects: {stats['unique_projects']}")
    print(f"Unique generators: {stats['unique_generators']}")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print()
    print(_DIVIDER)
    print("  AI Company OS -- Artifact Generation Engine Demo")
    print("  Sprint 16")
    print(_DIVIDER)
    print()

    engine, project_id = setup_engines()
    print()

    demo_prd(engine, project_id)
    demo_technical_spec(engine, project_id)
    demo_api_spec(engine, project_id)
    demo_ceo_report(engine)
    demo_engine_history(engine)

    print(_DIVIDER)
    print("  Demo complete.")
    print(_DIVIDER)
    print()


if __name__ == "__main__":
    main()
